version: 1.0.{build}

clone_script:
  - cmd: git clone --recursive --depth 1 --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

image: Visual Studio 2017

build:
  parallel: true

platform: [ x86, x64 ]

configuration: [ Release, Debug ]

build_script:
  - ps: |
      msbuild @{"x86"="vs/odbc32.sln";"x64"="vs/odbc64.sln"}[$env:PLATFORM]

deploy_script:
   - ps: |
       Push-AppveyorArtifact ( "vs\installer{1}\bin\{0}\clickhouse_odbc_x{1}.msi" -f $env:Configuration, @{"x86"="32";"x64"="64"}[$env:PLATFORM] )
